In [0]:
from keras import models
from keras import layers
from keras.datasets import mnist
from keras.utils import to_categorical

In [0]:
# load MNIST dataset
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

## Understand the Data

In [33]:
print('The shape of the training images: ', train_images.shape)
print('The shape of the training labels: ', train_labels.shape)
print('The shape of the testing images: ', test_images.shape)
print('The shape of the testing labels: ', test_labels.shape)

The shape of the training images:  (60000, 28, 28)
The shape of the training labels:  (60000,)
The shape of the testing images:  (10000, 28, 28)
The shape of the testing labels:  (10000,)


In [34]:
# The first digit in the training set is 5
train_labels[0]

5

In [35]:
# This is how it looks like after vectorisation
train_images[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [36]:
# Basically it's transformed from an image into a 28 by 28 matrix
train_images[0].shape

(28, 28)

## Build a Neural Network

In [0]:
# set up a network
network = models.Sequential()

# add a fully connected layer (a.k.a Dense layer) with a 28 * 28 input shape 
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))

# add a fully connected layer which returns an array of 10 probability scores that signifies which digit class it belongs to
network.add(layers.Dense(10, activation='softmax'))

# compilation: loss function, optimiser, evaluation metrics
network.compile(optimizer = 'rmsprop', 
                loss = 'categorical_crossentropy', 
                metrics=['accuracy'])

## Data Preprocessing

In [0]:
# reshape and rescale the data to the form that the network expects
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

In [38]:
train_images[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [0]:
# take care of labels as well
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [44]:
train_labels[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

## Train the model

In [45]:
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Instructions for updating:
Use tf.cast instead.
Epoch 1/5
60000/60000 [==============================] - 4s 69us/step - loss: 0.2542 - acc: 0.9266
Epoch 2/5
60000/60000 [==============================] - 2s 32us/step - loss: 0.1010 - acc: 0.9699
Epoch 3/5
60000/60000 [==============================] - 2s 32us/step - loss: 0.0668 - acc: 0.9799
Epoch 4/5
60000/60000 [==============================] - 2s 33us/step - loss: 0.0494 - acc: 0.9850
Epoch 5/5
60000/60000 [==============================] - 2s 32us/step - loss: 0.0378 - acc: 0.9884


## Evaluate the model

In [46]:
test_loss, test_acc = network.evaluate(test_images, test_labels)
print('test_acc:', test_acc)

10000/10000 [==============================] - 0s 49us/step
test_acc: 0.98
